#encoding: utf-8
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development: 
  adapter: mysql2
  encoding: utf8
  database: atlas_development
  username: atlas
  password: atlas_password
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: production_database_name
  username: production_user
  password: production_user_password
  host: 127.0.0.1
  port: 3306